(define (make-monitored fn)
  (let ((counter 0))
    (define (dispatch m)
      (cond ((eq? m 'how-many-calls?) counter)
            ((eq? m 'reset-count) (begin (set! counter 0) 0))
            (else (set! counter (+ 1 counter)) (fn m))))
    dispatch))

(define s (make-monitored sqrt))
(s 100)
(s 100)
(s 'how-many-calls?)
(s 'reset-count)
(s 'how-many-calls?)

(s 100)
(s 100)
(s 'how-many-calls?)
(s 'reset-count)
(s 'how-many-calls?)
